-- local config = {
--   mappings = {
--     ["<Space>r"] = require("runner.run").start,
--     ["<Space>R"] = require("runner.run").stop,
--   },
--   ignored_fts = {
--     oil = true,
--     cmp_menu = true,
--   },
--   debug = false,
--   lang = require("runner.lang")
-- }
